version: "3"

x-dev-base: &dev-base
  build:
    context: .
    dockerfile: ./docker/Dockerfile
  environment: 
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-hogehoge}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-hogehoge}
  volumes: 
    - ./terraform:/infra/terraform

services:
  stg:
    << : *dev-base
    working_dir: /infra/terraform/env/stg
  
  prod:
    << : *dev-base
    working_dir: /infra/terraform/env/prod